GOSSIP_DATA = {
    "Jerico": "Lives in Barcelona since he is 2. co president of 180dc. born in Phillipines. did the Dubai study trip. Gym bro in the free time.",
    "Borisa": "From Serbia. has a sister. did the Seoul study trip. punched someone in a club in Seoul?",
    "Sabeena": "from Germany. has a boyfriend. worked in private equity. does modeling. did the Seoul trip.",
    "Mateo Barreda": "from Bolivia. has a French girlfriend. def a morning person - morning sunshine. always happy and energetic. studied in Germany before - Munich. did the Cape Town trip.",
    "Gianluca": "from Como. has a girlfriend. wants to work in finance. did the Dubai trip. lives in Sant Gervasi. does dj. Sant Gallen?. Damiano David twin.",
    "Francesc Cañavate": "catalan. color blind. has a russian girlfriend. did the India trip. has siblings. plays instruments. night owl. team coffee. has technical background. team beer. Passion for tall women (?).",
    "Lorenzo": "Fake swiss but Italian in heart. doesn’t have swiss citizenship. from Verona. always late. studied in London before. Wewe (French) LOWENZO.",
    "Brice Da Costa": "Luxembourg. talks 5 languages. class rep. has a girlfriend. has pets. night owl. team tea. studied in Amsterdam before. team beer.",
    "Mo Aymen": "ZAYLUNE! from Casablanca. sits in the back. did bachelors in ESADE. Seoul trip.",
    "Baran": "Turkish from Ist. studied in USA before.",
    "Botond": "Hungarian.",
    "Sara Fibla": "Information not detailed in notes.",
    "Giorgio Fiorentino": "Fiore. Information not detailed.",
    "Yiben Fruncillo": "VENEZIA. future st gallen alumni. india trip. single. night owl. has tattoos. team tea.",
    "Jan Philipp": "Information not detailed in notes.",
    "Pau": "catalan. has a brother also in ESADE. did the india trip. running club FOUNDER. high volume nose cleaning in class.",
    "Matteo Guardamagna": "Padel boss. Milan. Ferragnez neighbour. India trip. Cems Australia. Micromamba. in a relationship. has siblings. has pets. night owl. team coffee. wears glasses while study. front row.",
    "Lucas Joris": "Belgium. did bachelors in ESADE. seoul trip. single. night owl. team coffee. team beer. has 2 sisters.",
    "Sean": "singapore. half Belgian ?. studied in Australia. has a Dutch girlfriend. every morning eats granola with yogurt. such as sales person. has siblings. night owl. team coffee. team beer. has pets.",
    "Mats": "Information not detailed in notes.",
    "Fabrizio Iacuzio": "watched thai women ping pong show. seoul trip. does hackathon. southern italian. bocconi alumni. we on member. strong italian accent. single. has pets. lost the esade fight.",
    "May": "Information not detailed in notes.",
    "Riwad": "Information not detailed in notes.",
    "Lara Isikci": "Information not detailed in notes.",
    "Vera": "Information not detailed in notes.",
    "Jakob": "Information not detailed in notes.",
    "Warren": "Comes late to class.",
    "Wouter": "Has a twin. Is a ginger.",
    "Ella Magdic": "loves listening bars. does dj. from Croatia. studied in Amsterdam. has pets. has siblings. night owl. has tattoos. team tea. loves slavic girl breakfast. team beer. does hackathon.",
    "Miguel de Faria": "half spanish half portuguese. has a boyfriend. has siblings. early bird. has a case for banana. coffee team. likes spicy food. india trip. late to class. team beer.",
    "Abhay": "accidentally painted the class wall.",
    "Leo": "magnanimous.",
    "Simon": "Information not detailed in notes.",
    "Gabriela Méndez": "from Mexico. has a boyfriend. seoul trip. has pets. early bird. team tea.",
    "Alessandro": "Information not detailed in notes.",
    "Amat Montoto": "running club. has a girlfriend. catalan. has siblings. plays instruments. early bird. team coffee. wear glasses. india trip. team beer.",
    "Kika": "loves pilates. from Chile. study tour student rep. has siblings. has pets. single. early bird. team tea. wears glasses. team beer.",
    "Hiroaki Nakano": "married. seoul trip. from Japan. has siblings. plays instruments. early bird. team coffee. team beer.",
    "Florian Nix": "german and bosnian. has a girlfriend. has siblings. night owl. loves lego and building lego too. team coffee.",
    "Maria París": "catalan. from Barcelona. has a boyfriend. team tea. team vermut. has 2 brothers. early bird. face of miba.",
    "Ana": "Information not detailed in notes.",
    "Francesco Polimeni": "has siblings. has pets. single. night owl. team tea. likes bonus points. CEMS hong kong. front row. Bocconi.",
    "eng pongtanya": "from Thailand. single. india trip. lives in Sant Cugat. only child. has pets. night owl. has tattoos. team coffees. loves traveling. team beer.",
    "Petter": "Information not detailed in notes.",
    "David Puchala": "Czech. studied in Amsterdam before. has a bulgarian girlfriend. lived in Sant Cugat. LOVES indian food. has siblings. back row team. has pets. early bird. every week goes to sevilla. team tea. comes late. team beer. india trip.",
    "Ayush Raj": "lives in Sant Cugat. from India. has siblings. loves (in love) the AI video teacher. single. night owl. has tattoos. coffee. likes spicy food. team Vermut.",
    "Andres": "from Mexico. Seoul trip. single.",
    "Ferdinand": "Information not detailed in notes.",
    "Sharath Raveendran": "from Bangalore. single. only child. night owl. team tea.",
    "Pedro": "from portugal. front row. doesn’t like spanish food. from NOVA lisbon. st gallen double degree. dropped spanish class.",
    "Georgii": "Information not detailed in notes.",
    "Mara": "has a twin.",
    "Sara Saleem": "Information not detailed in notes.",
    "Ivan": "Information not detailed in notes.",
    "Marc Sardà": "catalan. learned english before 5 months the course. has siblings. single. night owl. has tattoos. team coffee. india trip. team beer.",
    "Alex": "is a ginger.",
    "Federica": "Information not detailed in notes.",
    "Samreen": "Information not detailed in notes.",
    "Jan": "Information not detailed in notes.",
    "Omar Trabelsi": "from Rabat - Morrocco. studied bachelers in ESADE. engaged. seoul trip. has siblings. did exchange in WHU Germany. night owl. team tea. team soft drink.",
    "Patricia": "Information not detailed in notes.",
    "Carlos": "birthday celebrated in 4 latas on a 20th of March.",
    "Max": "Information not detailed in notes.",
    "Aumkar": "Information not detailed in notes.",
    "Carolina": "Information not detailed in notes.",
    "Jad Zoghaib": "Information not detailed in notes."
}
